# Generated by Django 3.2.9 on 2021-11-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Carros', '0002_auto_20211106_1432'),
        ('Clientes', '0002_alter_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('valor', models.CharField(max_length=50)),
                ('observacoes', models.CharField(max_length=200)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carros.carro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
            ],
        ),
    ]
